### ISSUE TITLE
Grade Feedback ERROR

### ISSUE THREAD

**Issue by d0uble3L** [Pray-d/Disaster-Risk-Monitoring-Using-Satellite-Imagery#1]
Getting the following error.

Step1: ERROR bad report; SCORE 0 of 60 
Total Score 0 of 60

My answer.txt is 
0.06

Any feedback on how you were able to successfully complete the course?

**Comment by d0uble3L** [comment]
Nevermind - figured out mistake

**Comment by Rajnish-rj07** [comment]
> Nevermind - figured out mistake

Can you please gave me solution I'm facing same issue with this code help me if possible
